CHANGELOG.md
README.md
lib/src/cloud_firestore_mocks_base.dart
lib/src/mock_document_reference.dart
lib/src/mock_field_value_factory_platform.dart
lib/src/mock_field_value_platform.dart
pubspec.yaml
test/cloud_firestore_mocks_test.dart

Support FieldValue.delete()

---

lib/src/mock_document_reference.dart
test/cloud_firestore_mocks_test.dart

Fixes #15 .
@atn832 Would you review this?  This still needs to handle more edge cases such as deleting the last field of a object, but I'd like to confirm the overall direction with you.

Support nested documents

---

README.md
lib/src/mock_write_batch.dart
lib/src/write_task.dart
test/cloud_firestore_mocks_test.dart

Batch to support updateData and delete operation

---

lib/src/cloud_firestore_mocks_base.dart
lib/src/mock_collection_reference.dart
lib/src/mock_document_reference.dart
lib/src/mock_document_snapshot.dart
lib/src/mock_query.dart
test/cloud_firestore_mocks_test.dart

MockFirestoreInstance to remember saved documents

---

example/test_driver/cloud_firestore_behaviors.dart
lib/src/mock_document_reference.dart
test/cloud_firestore_mocks_test.dart

Updating a document should not affect previously-retrieved snapshots

---

README.md
example/test_driver/cloud_firestore_behaviors.dart
lib/src/cloud_firestore_mocks_base.dart
test/cloud_firestore_mocks_test.dart

Support runTransaction that sequentially executes the oprations without rollback feature

---

example/test_driver/cloud_firestore_behaviors.dart
lib/src/cloud_firestore_mocks_base.dart
lib/src/mock_document_reference.dart
lib/src/mock_field_value_factory_platform.dart
lib/src/mock_field_value_platform.dart
test/cloud_firestore_mocks_test.dart

FieldValue.increment, arrayUnion, and arrayRemove

---

lib/src/util.dart
test/cloud_firestore_mocks_test.dart

getSubpath to handle path that contains slashes

---

lib/src/mock_collection_reference.dart
lib/src/mock_document_reference.dart
test/cloud_firestore_mocks_test.dart
test_driver/field_value_behaviors.dart

Overriding parent, path, firebase, and equals methods

---

test_driver/cloud_firestore_behaviors.dart

Fixes #58.
Test logs before: https://gist.github.com/atn832/5dcae11307d4c59de143a3259dbb87cf
Test logs after: https://gist.github.com/atn832/9b4106ea68b8e9a5f228bd812a0a3d66

Remove cast to Map<string, dynamic>

---

lib/src/mock_document_snapshot.dart
test/cloud_firestore_mocks_test.dart

Fixes #79 
This is likely not the right way to fix the referred issue. I am open to suggestions :)

Make MockDocumentSnapshot data immutable

---

lib/src/mock_query.dart
test/mock_query_test.dart
test_driver/cloud_firestore_behaviors.dart

Support null values in orderBy

---

lib/src/mock_document_reference.dart
test/cloud_firestore_mocks_test.dart

Support FieldValue in nested objects

---

README.md

solve https://github.com/atn832/cloud_firestore_mocks/issues/94

Add a badge to the readme

---

lib/src/mock_query.dart
test/mock_query_test.dart

Fix remaining points of https://github.com/atn832/cloud_firestore_mocks/pull/112
- fix typo
- fix a wrong comment

Fix comments and typo

---

.github/workflows/dart-format.yaml
test_driver/cloud_firestore_behaviors.dart

Because I don't want to consider format, I added dart format check workflow.
I you like, please consider merge.

Dart format

---

.gitignore
example/android/local.properties

Every time I run `flutter pub get`, diff occures. So, I added _minimum_ ignore.
Ref. https://github.com/flutter/flutter/blob/master/.gitignore#L58-L67

gitignore anrdoid local.properties

---

.github/workflows/analyzer.yaml
example/lib/main.dart
example/test/widget_test.dart
example/test_driver/cloud_firestore.dart
example/test_driver/cloud_firestore_test.dart
lib/src/cloud_firestore_mocks_base.dart
lib/src/mock_collection_reference.dart
lib/src/mock_document_reference.dart
lib/src/mock_query.dart
lib/src/util.dart
pubspec.yaml
test/cloud_firestore_mocks_test.dart
test/document_snapshot_matcher.dart
test/query_snapshot_matcher.dart
test_driver/cloud_firestore_behaviors.dart
test_driver/cloud_firestore_behaviors_test.dart
test_driver/field_value_behaviors.dart
test_driver/field_value_behaviors_test.dart
test_driver/firestore_clients.dart

solve https://github.com/atn832/cloud_firestore_mocks/issues/117
* I separted alanyzer workflow from unit test workflow, because I want to show the workflow commit status besides unit tests.
* follow https://pub.dev/packages/pedantic analysis_options which has been already commited.

Add analyzer workflow and fix analyzer issues

---

example/pubspec.yaml
pubspec.yaml

upgrade dependencies targeting at minor/patch version.
This upgrade is _preparation_ for https://github.com/atn832/cloud_firestore_mocks/issues/125
@atn832  please review 🚀

upgrade dependencies. minor version.

---

lib/src/mock_collection_reference.dart
lib/src/mock_query.dart
test/cloud_firestore_mocks_test.dart

Fix collectionGroup "entries was called on null error"

---

.gitignore
CHANGELOG.md
lib/src/mock_document_snapshot.dart
lib/src/mock_snapshot_metadata.dart
pubspec.yaml
test/mock_query_test.dart

In order to test code which use metadata, it's necessary to add metadata map to documents mockup

Added metadata data in documents mock

---

analysis_options.yaml
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
example/analysis_options.yaml
example/lib/main.dart
example/pubspec.yaml
example/test_driver/cloud_firestore.dart
pubspec.yaml
test_driver/cloud_firestore_behaviors.dart
test_driver/firestore_clients.dart

By using dependency_overrides, I can avoid dependency conflicts from flutter_driver.

fix compilation issues in integration tests

---

CHANGELOG.md
lib/src/cloud_firestore_mocks_base.dart
lib/src/converter.dart
lib/src/mock_collection_reference.dart
lib/src/mock_document_reference.dart
lib/src/mock_document_snapshot.dart
lib/src/mock_query.dart
lib/src/mock_query_document_snapshot.dart
lib/src/mock_query_snapshot.dart
pubspec.yaml
test/cloud_firestore_mocks_test.dart

Converters

---

lib/src/mock_write_batch.dart
test/mock_batch_test.dart

clean up batch tests

---

.github/workflows/dart-format.yaml

fixed dart format workflow

---

lib/src/mock_query.dart
test/mock_query_test.dart

Make tests introduced in https://github.com/atn832/fake_cloud_firestore/pull/215 pass.

Fix ordered by

---

lib/src/mock_query.dart

Cleans up #216.
To do this, I reworked `_cursorUtil` to correctly find indexes. `_cursorUtil` looks for the index of the last element which is smaller than the given list of key/values. However the previous code looked at each value individually and as a result missed some corner cases. This one implements proper element comparison.

Reuse subquery method for startAt and endAt

---

lib/src/mock_query.dart
test/mock_query_test.dart

Adds the option to create a query using the `whereNotIn` selector.

Implement querying using whereNotIn

---

README.md
example/pubspec.yaml
lib/src/fake_aggregate_query.dart
lib/src/fake_aggregate_query_snapshot.dart
lib/src/mock_query.dart
pubspec.yaml
test/mock_query_test.dart

Implemented Query.count, switch to Firestore 4.0

---

CHANGELOG.md
lib/src/fake_converted_query.dart
pubspec.yaml
test/mock_query_test.dart

I missed this use case in #245.
#244.

Implemented count for converted queries

---

lib/src/mock_document_reference.dart

Changed `cloud_firestore/not-found` to `not-found`.

Updated Firebase exception code to one that matches real code

---

lib/src/mock_query.dart
test/mock_query_test.dart

Fix #180 'Null' is not a subtype of type 'Comparable' in type cast issue

---

CHANGELOG.md
README.md
lib/src/mock_document_reference.dart
pubspec.yaml
test/fake_cloud_firestore_test.dart

Enable DocumentReference.set to throw exceptions

---

lib/src/mock_collection_reference.dart
lib/src/mock_document_reference.dart
lib/src/query_snapshot_stream_manager.dart
test/mock_query_test.dart

Also cleaned up the tests so they return meaningful error messages if it ever fails.

fixed rare misfires of updates

---

CHANGELOG.md
android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
pubspec.yaml

Upgrade dependencies' major versions

---

CHANGELOG.md
README.md
lib/src/mock_document_reference.dart
pubspec.yaml
test/fake_cloud_firestore_test.dart

implement MockDocumentReference.hashcode

---

lib/src/query_snapshot_stream_manager.dart
test/query_snapshot_stream_manager.dart

Fixes our own issue, which is the same as https://github.com/atn832/fake_cloud_firestore/issues/263

Fix: concurrent list modification

---

lib/src/fake_cloud_firestore_instance.dart
lib/src/mock_collection_reference.dart
lib/src/mock_document_reference.dart
lib/src/mock_query.dart
pubspec.yaml

Based on https://github.com/flutter/engine/pull/38663/files

fix: analyzer issues

---

CHANGELOG.md
README.md
example/pubspec.yaml
pubspec.yaml

upgrade to Firestore 5.0.0

---

example/pubspec.yaml

Fixes the unit test workflow issue from #325

updated example pubspec
