atn832/fake_cloud_firestore

- lib/src/mock_document_reference.dart
- test/cloud_firestore_mocks_test.dart
https://github.com/atn832/cloud_firestore_mocks/pull/4/commits/c684c1407e183750e6f1720e9f2b431cf1e0f445
```dart
firestore
.collection('userProfiles')
.document(datumId)
.snapshot()
```
Before:  return `null`
After:  return `Stream<DocumentSnapshot>`
> feat: add single document snapshot on stream

- lib/src/mock_document_snapshot.dart
- test/cloud_firestore_mocks_test.dart
Ran into an issue where if I was using the `exists` property in code I was testing it would throw a run time error because `exists` is defined as a bool but since its never initialized the value returned is null. This PR sets the `exists` property to true if there is data at the path or false if not. Thank you for this library its really really helpful!
> set DocumentSnapshot exists property

- CHANGELOG.md
- example/ios/Runner/GeneratedPluginRegistrant.m
- example/pubspec.yaml
- lib/src/mock_collection_reference.dart
- lib/src/mock_document_reference.dart
- lib/src/mock_query.dart
- lib/src/util.dart
- pubspec.yaml
https://pub.dev/packages/cloud_firestore#0100 removed `FieldValue.type` and `FieldValue.value` from the public API. So the mocks can't read their values anymore. To fix the breakage more quickly, I'll remove support for `FieldValue.delete()` for now.
> Fix breakage from API change in cloud_firestore 0.10.0

- lib/src/mock_document_reference.dart
- lib/src/mock_field_value_factory_platform.dart
- lib/src/mock_field_value_platform.dart
- test/cloud_firestore_mocks_test.dart
> Mock FieldValue.serverTimestamp() with Timestamp.now()

- lib/src/mock_collection_reference.dart
- lib/src/mock_document_reference.dart
- test/cloud_firestore_mocks_test.dart
Fixes #14 .
Due to complexity in updating tests, I left the behavior of `document.add` unchanged. For example, https://github.com/atn832/cloud_firestore_mocks/pull/22/files#diff-e8ee19ddcfe4302627bdf8313dad3f9bR280 Expecting document ID “zz”
> Auto ID for document()

- lib/src/mock_collection_reference.dart
- lib/src/mock_field_value_factory_platform.dart
- lib/src/mock_field_value_platform.dart
- test/cloud_firestore_mocks_test.dart
Once this PR is merged, I can run "flutter format" to format my changes without touching other files.
```
~/Documents/cloud_firestore_mocks $ flutter format
Formatting directory .:
Formatted test/cloud_firestore_mocks_test.dart
Unchanged example/test_driver/cloud_firestore_test.dart
Unchanged example/test_driver/cloud_firestore.dart
Unchanged example/test/widget_test.dart
Unchanged example/lib/main.dart
Unchanged lib/cloud_firestore_mocks.dart
Unchanged lib/src/util.dart
Formatted lib/src/mock_field_value_factory_platform.dart
Unchanged lib/src/mock_document_reference.dart
Formatted lib/src/mock_field_value_platform.dart
Unchanged lib/src/cloud_firestore_mocks_base.dart
Unchanged lib/src/write_task.dart
Unchanged lib/src/mock_query.dart
Formatted lib/src/mock_collection_reference.dart …
```
> Flutter format

- lib/src/mock_collection_reference.dart
- test/cloud_firestore_mocks_test.dart
- test/document_snapshot_matcher.dart
- test/mock_query_test.dart
Fixes #23
- addData to use automatic documentID generation
- New `DocumentSnapshotMatcher.onData` to create a matcher that does not verify documentID.
> addData to use automatic documentID generation

- lib/src/mock_collection_reference.dart
- lib/src/mock_query.dart
- test/mock_query_test.dart
Fixes #31 
MockQuery should not hold the query results; otherwise it may return stale data.
In my use case, my class hold a collection reference (a final field) during the whole lifetime of my app. The class adds and retrieves documents from the Firestore collection through the the same reference.
> MockQuery to defer query execution until getDocuments

- lib/src/cloud_firestore_mocks_base.dart
- test/cloud_firestore_mocks_test.dart
Fixes #30 
This is to simulate the error in the issues. Firebase users encounter similar errors https://stackoverflow.com/questions/46639058/firebase-cloud-firestore-invalid-collection-reference-collection-references-m . Detecting such mistake in widget tests is beneficial to Firebase users' developer experience.
> Assert the number of segment in MockFirestoreInstance's document() and collection()

- lib/src/mock_collection_reference.dart
- lib/src/mock_document_reference.dart
- test_driver/cloud_firestore_behaviors.dart
Fixes #51 
Supported data types: https://firebase.google.com/docs/firestore/manage-data/data-types
> Validation on Firestore Supported Data Types

- lib/src/mock_query.dart
- test/mock_query_test.dart
Adds support for `arrayContains`. This assumes that the correct behavior for using arrayContains on a field that is not of an array type is to not match any documents. This appears to be how it works in the JS SDK at least but I could not find a reference that explicitly states that.
> add support for arrayContains in where

- README.md
- test_driver/cloud_firestore_behaviors.dart
Fixes #71 
I am a little unclear on how to run this test on the android emulator to make sure its working. The [readme](https://github.com/atn832/cloud_firestore_mocks/tree/master/test_driver#run-driver-test) says to run in the example folder but the `cloud_firestore_behaviors.dart` file doesn't exist there.
> Adds driver test for arrayContains

- lib/src/mock_query.dart
- test/mock_query_test.dart
Fixes #67 
This change will allow to use `whereIn` operator with query.where
See official Firestore documentation for more details:
https://firebase.google.com/docs/firestore/query-data/queries#in_and_array-contains-any
> Add support for whereIn query

- lib/src/mock_document_reference.dart
- lib/src/mock_document_snapshot.dart
Fixes atn832/cloud_firestore_mocks#83
> Always do a deep copy of the data when creating a MockDocumentSnapshot.

- .gitignore
- lib/src/mock_document_change.dart
- lib/src/mock_snapshot.dart
- test/cloud_firestore_mocks_test.dart
Expand `MockSnapshot` to support the `documentChanges` API.
This adds support for added documents only, as `fireSnapshotUpdate` won't fire for other events.
Regards
> Mock Document Changes

- example/android/local.properties
- lib/src/mock_collection_reference.dart
- lib/src/mock_document_reference.dart
- lib/src/mock_query.dart
- pubspec.yaml
- test/mock_query_test.dart
Fix the issue #111 
- Add `QuerySnapshotStreamManager` to keep and re-fire updated data to streams for each `Query`.
- Setup `snapshots()` stream to not broadcast same data.
- Add unit test
> Correctly setup `MockQuery.snapshots()` to broadcast data to 'already listening' streams.

- example/test_driver/cloud_firestore.dart
- lib/src/mock_document_change.dart
- lib/src/mock_query.dart
- lib/src/mock_snapshot.dart
- test/cloud_firestore_mocks_test.dart
solve https://github.com/atn832/cloud_firestore_mocks/issues/120 **_partialiy_**.
on this PR, to implement [DocumentChangeType](https://pub.dev/documentation/cloud_firestore_platform_interface/latest/cloud_firestore_platform_interface/DocumentChangeType-class.html) other than `added` is not supported.
> support oldIndex,newIndex of DocumentChange

- lib/src/mock_query.dart
- test/mock_query_test.dart
> Add FieldPath.documentId support in MockQuery.where & MockQuery.orderBy

- lib/src/cloud_firestore_mocks_base.dart
- lib/src/mock_collection_reference.dart
- lib/src/mock_document_reference.dart
- test/cloud_firestore_mocks_test.dart
A document may contain a key and a sub-collection with the same name: they should not conflict.
By having separate namespaces for data and sub-collections, this also fixes #90: indeed, updating a document's data without setting the merge flag won't remove sub-collections.
One limitation is the `dump()` function of the `MockFirestoreInstance` class: because it rerturns a single tree, precedence is given to the sub-collection is there is a name conflict between a sub-collection and a key in the data.
Fixes #90.
> Use different namespace for collections and documents' data

- lib/src/cloud_firestore_mocks_base.dart
- lib/src/mock_collection_reference.dart
- lib/src/mock_query.dart
- lib/src/util.dart
- test/cloud_firestore_mocks_test.dart
- test/util_test.dart
solve https://github.com/atn832/cloud_firestore_mocks/issues/107
support [CollectionGroup Query](https://firebase.google.com/docs/firestore/query-data/queries#collection-group-query)
* add `isCollectionGroup` flag on MockCollectionReference in imitaion of [Firestore offical plugin implementation](https://github.com/FirebaseExtended/flutterfire/search?q=isCollectionGroup&type=)
* Especially, I would like you to review 2 points.
* `getSubpath()` returns _all paths which contain "collectionId"_
* By solving path of DocumentReference In `getDocuments()`, DocumentReference also works expectedly.
> support CollectionGroup Query

- .github/workflows/unit-tests.yaml
- .gitignore
- example/README.md
- example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
- example/android/build.gradle
- example/android/gradle/wrapper/gradle-wrapper.properties
- example/ios/Runner.xcodeproj/project.pbxproj
- example/ios/Runner/GeneratedPluginRegistrant.m
- example/lib/main.dart
- example/pubspec.yaml
- example/test_driver/cloud_firestore.dart
- lib/src/cloud_firestore_mocks_base.dart
- lib/src/mock_collection_reference.dart
- lib/src/mock_document_change.dart
- lib/src/mock_document_reference.dart
- lib/src/mock_document_snapshot.dart
- lib/src/mock_query.dart
- lib/src/mock_query_document_snapshot.dart
- lib/src/mock_snapshot.dart
- lib/src/mock_write_batch.dart
- pubspec.yaml
- test/cloud_firestore_mocks_test.dart
- test/document_snapshot_matcher.dart
- test/mock_query_test.dart
- test/query_snapshot_matcher.dart
- test_driver/cloud_firestore_behaviors.dart
- test_driver/field_value_behaviors.dart
- test_driver/firestore_clients.dart
support cloude_firestore 0.14 version.
From the version, we have to migrate. See: https://firebase.flutter.dev/docs/migration
This PR resolve https://github.com/atn832/cloud_firestore_mocks/issues/125.
Although **I made meaningful commit mesaages and separated commits based on migration step as far as possible**, diff is very big.
1. https://github.com/sensuikan1973/cloud_firestore_mocks/pull/4/commits/bbfe14183328d3d08a21ab145981e81abbd8e2a4: update-firebase-plugins
2. https://github.com/sensuikan1973/cloud_firestore_mocks/pull/4/commits/510bf084c9efc6018ba66d38e26be522b8a3ae92: platform-setup
3. https://github.com/sensuikan1973/cloud_firestore_mocks/pull/4/commits/3957cdb658239447c807e79e776f2484324712d6: follow breaking/new changes
4. …
> [Migration] support cloud_firestore 0.14.x

- lib/src/cloud_firestore_mocks_base.dart
- test/cloud_firestore_mocks_test.dart
resolve https://github.com/atn832/cloud_firestore_mocks/issues/129
I changed Transaction in https://github.com/atn832/cloud_firestore_mocks/pull/127/files#diff-f88a1580752ecb4e5e77d48fd3ef7cfcL75.
The background is **https://github.com/FirebaseExtended/flutterfire/commit/27d574e620c3a95792682397b12e54e40abe572f#diff-4b03d320cd06661a52dd22772cf78abfL82-R181**
But, I also had to change the return value of runTransaction.
> fix runTransaction return type bug

- lib/src/mock_document_reference.dart
- test/cloud_firestore_mocks_test.dart
Returns a stream that reacts to changes in document value.
> Implement MockDocumentReference.snapshots()

- example/pubspec.yaml
- lib/src/cloud_firestore_mocks_base.dart
- lib/src/mock_collection_reference.dart
- lib/src/mock_collection_reference_platform.dart
- lib/src/mock_document_change.dart
- lib/src/mock_document_reference.dart
- lib/src/mock_document_reference_platform.dart
- lib/src/mock_document_snapshot.dart
- lib/src/mock_query.dart
- lib/src/mock_query_document_snapshot.dart
- lib/src/mock_query_platform.dart
- lib/src/mock_write_batch.dart
- lib/src/write_task.dart
- pubspec.yaml
- test/cloud_firestore_mocks_test.dart
- test/document_snapshot_matcher.dart
Support null-safety.
I had to temporarily disable integration tests by removing the dependency to flutter_driver for it to work. Otherwise I get dependency errors on `flutter pub get`:
```
[cloud_firestore_mocks] flutter pub get
Running "flutter pub get" in cloud_firestore_mocks...           
Because analyzer >=1.0.0 depends on args ^2.0.0 and every version of flutter_driver from sdk depends on args 1.6.0, analyzer >=1.0.0 is incompatible with flutter_driver from sdk.
And because mockito >=5.0.0 depends on analyzer ^1.0.0, flutter_driver from sdk is incompatible with mockito >=5.0.0.
So, because cloud_firestore_mocks depends on both mockito ^5.0.0 and flutter_driver any from sdk, version solving failed.
pub get failed (1; So, because cloud_firestore_mocks depends on both mockito ^5.0.0 …
```
> support null-safety

- lib/src/mock_query_document_snapshot.dart
- test/mock_query_test.dart
- test_driver/cloud_firestore_behaviors.dart
Fix Query Snapshot that returns a non nullable type from this PR https://github.com/FirebaseExtended/flutterfire/pull/5476
I tested this by using in my pubspec.yaml file and works 
```
cloud_firestore_mocks: 
git:
url: git@github.com:lyledean1/cloud_firestore_mocks.git
ref: fix-mocks
```
> Fix Query Snapshot To Return a Non Nullable Type

- lib/src/mock_document_snapshot.dart
- test/mock_query_test.dart
Hi @atn832,
this is the follow up of PR #155 which adds support for queries with composed keys.
When i tried writing some more tests, i noticed a few more minor issues:
* Queries with IsNull are not yet supported
* Queries with a composed key that does not exist (hence returns a null value) will fail as null is tried to cast to Comparable.
I have fixed them but i guess i should better put them in separate PRs as they are not only related to queries with composite keys?
Therefore some tests regarding the composite key feature are missing (query with a composite key that does not exist + query with isNull).
Regards,
Alex
> Support queries using composite keys

- lib/src/mock_query.dart
- test/mock_query_test.dart
@atn832, this resolves issue #140.
Added support for:
* isNotEqualTo
* isNull
in class MockQuery.
Regards, 
Alex
> Add support for isNotEqualTo and isNull where clause conditions

- lib/src/mock_document_snapshot.dart
- test/mock_query_test.dart
There is a null pointer exception when query using `where()` cause with nested fields where the top-level name is missing.
e.g: `collectionReference.where('user.age', isEqualTo: 18);`
This query will failed if `user` is null.
> Fix null pointer exception

- CHANGELOG.md
- README.md
- example/pubspec.yaml
- lib/src/cloud_firestore_mocks_base.dart
- lib/src/mock_collection_reference.dart
- lib/src/mock_document_change.dart
- lib/src/mock_document_reference.dart
- lib/src/mock_document_snapshot.dart
- lib/src/mock_query.dart
- lib/src/mock_query_document_snapshot.dart
- lib/src/mock_query_snapshot.dart
- lib/src/mock_write_batch.dart
- lib/src/write_task.dart
- pubspec.yaml
- test/mock_query_test.dart
As documented at https://firebase.flutter.dev/docs/firestore/2.0.0_migration/, it requires using Generics everywhere.
Fixes #163.
All unit tests for the library pass.
Unit tests for the example app and Analyzer fail because of #157.
> Support cloud_firestore 2.1.0

- CHANGELOG.md
- README.md
- example/pubspec.yaml
- example/test/widget_test.dart
- lib/fake_cloud_firestore.dart
- lib/src/fake_cloud_firestore_instance.dart
- lib/src/mock_collection_reference.dart
- lib/src/mock_document_change.dart
- lib/src/mock_document_reference.dart
- lib/src/mock_document_snapshot.dart
- lib/src/mock_field_value_factory_platform.dart
- lib/src/mock_query_snapshot.dart
- pubspec.yaml
- test/fake_cloud_firestore_test.dart
- test/mock_query_test.dart
- test/util_test.dart
- test_driver/README.md
- test_driver/cloud_firestore_behaviors.dart
- test_driver/field_value_behaviors.dart
- test_driver/field_value_behaviors_parameters.dart
- test_driver/field_value_behaviors_test.dart
As per #34. Calling the library a cloud_firestore_mocks and its classes Mock* was misleading.
The migration for users should be effortless:
In pubspec.yaml file, replace `cloud_firestore_mocks: ^0.9.0` by `fake_cloud_firestore: ^1.0.0`.
Then in tests, replace:
```dart
import 'package:cloud_firestore_mocks/cloud_firestore_mocks.dart';
final firestore = MockFirestoreInstance();
```
By:
```dart
import 'package:fake_cloud_firestore/fake_cloud_firestore.dart';
final firestore = FakeFirebaseFirestore();
```
> Rename cloud_firestore_mocks to fake_cloud_firestore

- lib/src/fake_converted_query.dart
- lib/src/mock_collection_reference.dart
- lib/src/mock_document_reference.dart
- lib/src/mock_document_snapshot.dart
- lib/src/mock_query.dart
- lib/src/mock_query_document_snapshot.dart
- lib/src/mock_query_snapshot.dart
Tentative cleanup:
* separate regular Query and ConvertedQuery.
* move conversion from DocumentSnapshot to DocumentReference.
* move conversion from MockQuerySnapshot to MockQueryDocumentSnapshot.
* simplify MockQueryDocumentSnapshot to take only a docSnapshot and converter instead of 6 parameters.
* in CollectionReference, instead of manually creating DocumentSnapshots, use `DocumentReference.get()` to generate them.
> Clean up Converters

- lib/src/mock_write_batch.dart
- test/mock_batch_test.dart
batch has write restrictions. I added this code because this mock passes the test without the batch limitation.
https://firebase.google.com/docs/firestore/manage-data/transactions
>  Add confirmation of up to 500 document limits

- example/pubspec.yaml
- pubspec.yaml
The current latest version of fake_cloud_firestore does not run when combined with cloud_firestore version ^3.0.0.
This pull request just updates the cloud_firestore version used in the pub spec.yaml files to also enable working with cloud_firestore version ^3.0.0
> Update version of cloud_firestore to ^3.0.0

- lib/src/mock_document_reference.dart
When deleting a document the method `fireSnapshotUpdate` is called triggering a call to the converter (after some levels). The problem on calling the converter with the document as `_exists()` being false is that will trigger a null problem inside the converter (that requires non null values per Firebase lib). 
After looking the code I didn't understand the reasons on calling the `get()` method and subsequently the converter for a remove operation, so I added this verification before. All the tests are passing, so I hope this solves the issue #191.
> On removing document do not call the converter if document doesn't exists.

- lib/src/mock_document_reference.dart
- test/fake_cloud_firestore_test.dart
Fixes #196.
#192 introduced a regression where documents no longer fired an event when calling `doc.delete()`. This PR reintroduces the firing of the event. To prevent this issue from reoccurring, I implemented unit tests for it. Finally, since #191 reported some possible null exception when using converters, I also implemented unit tests using converters.
> fixed a regression: restored firing the event when calling doc.delete() and implemented tests

- lib/src/mock_document_reference.dart
- test/fake_cloud_firestore_test.dart
Fixes #191.
According to https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/FromFirestore.html, the converter should return a non-null value. So it is expected that the converter is always called with valid data.
So instead of expecting the converters to be able to handle document snapshots with no data, `MockDocumentReference.get()` will return a converted `MockDocumentSnapshot` with null data without calling the converter.
> do not call converter.convert when making a snapshot for a deleted document

- lib/src/mock_document_snapshot.dart
- test/fake_cloud_firestore_test.dart
The Firestore documentation at [https://googleapis.dev/nodejs/firestore/latest/DocumentSnapshot.html#get](https://googleapis.dev/nodejs/firestore/latest/DocumentSnapshot.html#get) shows you should be able to do gets like this `documentSnapshot.get('a.b')` to access child fields directly.  Here's a full example from that page:
> documentRef.set({ a: { b: 'c' }}).then(() => {
>   return documentRef.get();
> }).then(documentSnapshot => {
>   let field = documentSnapshot.get('a.b');
>   console.log(`Retrieved field value: ${field}`);
> });
This currently works in fake_cloud_firestore.  What's missing is that the spec says you should be able to use a FieldPath object instead of a String as the key.  The reason for this is that a field name can have dots in it.  So for example you may need to …
> add FieldPath support to doc.get()

- lib/src/mock_document_snapshot.dart
- lib/src/mock_query.dart
- test/fake_cloud_firestore_test.dart
- test/mock_query_test.dart
The existing notEqualTo query implementation ignores the specification at [https://firebase.google.com/docs/firestore/query-data/queries#not_equal_](https://firebase.google.com/docs/firestore/query-data/queries#not_equal_) part that says 
> Use the not equal (!=) operator to return documents where the given field exists and does not match the comparison value
The part that's not implemented is `the given field exists`.  This PR resolves that issue.  It also allows the use of FieldPath values to specify the field instead of just String values (which the real Firestore supports).
This PR also provides test to verify fixed functionality, including the use of FieldPath.  It requires the previous PR I created #205 in order to have FieldPath support.
> Fix notequalto query

- lib/src/mock_query.dart
- test/mock_query_test.dart
Make some tests that should fail, actually fail. The fact that the tests were engineered to succeed is concerning.
From those failing tests we can see that `orderBy` is failing, `endAt` and `startAt`
Side effect of closing https://github.com/atn832/fake_cloud_firestore/issues/204
> Make some tests that should fail, actually fail.

- lib/src/mock_document_reference.dart
- test/fake_cloud_firestore_test.dart
Hi all, this is my first time contributing to a public codebase, so please let me know if there's anything out of place here.
Previously the code worked under the assumption that if the new value for a given key was a map, and the key existed in the document, then the existing value was also a map. This is not always the case, as a value could be updated from an int to a map e.g. Admin.permissions = null => Admin.permissions = {deleteUser: False, createUser:True...}
In this case an unhandled TypeError is thrown and interrupts the update call.
This fix updates the code which identifies whether a given key already exists in the document for a new value of type map, and has it also check whether the existing value is of type Map. If either of these conditions is false, the key is assigned a …
> Fix bug with replacing non-map values with map

- lib/src/mock_collection_reference.dart
- lib/src/mock_document_reference.dart
- test/fake_cloud_firestore_test.dart
> `DocumentReference.update` throws an exception when the document does not exist

- CHANGELOG.md
- README.md
- lib/src/fake_cloud_firestore_instance.dart
- pubspec.yaml
Fixes #231.
Firestore 3.4.0 introduced a breaking change without changing the major version. So we do the same so that people who `flutter pub upgrade` get no compile issue.
> fixed compile issue due to firestore api change

- .gitignore
- android/local.properties
- lib/src/fake_converted_query.dart
- pubspec.yaml
- test/src/fake_converted_query_test.dart
`Query.limit` has not been implemented thus resulting in the following:
```
Class 'FakeConvertedQuery<Job>' has no instance method 'limit' with matching arguments.
Receiver: Instance of 'FakeConvertedQuery<Job>'
Tried calling: limit(11)
Found: limit(int) => Query<X0>
```
This PR provides a default `limit` implementation.
Fixes #198
> Add default Query.limit implementation

- lib/src/mock_document_reference.dart
- lib/src/mock_query.dart
- lib/src/util.dart
- test/mock_query_test.dart
**Summary**
- made sure that passing ```DateTime``` works with every applicable ```Query.where``` operator. I tested these types of queries on a real Firestore database and they all should work.
- improved support for data with lists. I don't know if this handles all the cases, but it fixed an issue in one of my projects.
- added tests for queries with ```DateTime```.
Fixes #228
> Support DateTime in other Query.where operators

- lib/src/mock_document_snapshot.dart
- lib/src/mock_field_value_platform.dart
- lib/src/mock_query.dart
- lib/src/util.dart
- test/fake_cloud_firestore_test.dart
**Summary**
This PR aims to make this package more consistent with original by solving some of the submitted issues.
* handle maps correctly when using ```FieldValue.arrayUnion``` or ```FieldValue.arrayRemove```, fixes #194 #234. This now works with dates too, though it was not submitted.
* throw when trying to save data with nested array, fixes #113.
* throw ```StateError``` when trying to access non-existent field with ```MockDocumentSnapshot.get```, fixes #165, #169.
> Fix inconsistencies with original plugin

- lib/src/mock_collection_reference.dart
- lib/src/mock_collection_reference_platform.dart
- lib/src/mock_document_reference.dart
- lib/src/mock_document_reference_platform.dart
- lib/src/mock_query.dart
- lib/src/mock_query_platform.dart
I had initially added those classes because the `noSuchMethod` pattern did not exist yet (or I was simply unaware of it).
```dart
@override
dynamic noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
```
> remove unused empty delegates

- lib/src/mock_field_value_platform.dart
- test/fake_cloud_firestore_test.dart
Base library makes it possible to compare ```FieldValue.delete()``` and ```FieldValue.serverTimestamp()```. The moment you call ```FakeFirebaseFirestore()``` it stops working, because it overwrites global ```FieldValueFactoryPlatform.instance``` with ```MockFieldValueFactoryPlatform```.
I added a test, it's basically the same as that one:
https://github.com/firebase/flutterfire/blob/cbb24aca7b1cfb264005e069e4377710a0f7b67f/packages/cloud_firestore/cloud_firestore/test/field_value_test.dart
> Fix FieldValue equality

- lib/src/util.dart
- test/fake_cloud_firestore_test.dart
Convert GeoPoint to a map so that `dump` does not crash if the fake firestore instance contains a GeoPoint object.
https://github.com/atn832/fake_cloud_firestore/issues/35
> Handle geopoint in encoder

- lib/src/mock_document_reference.dart
- test/fake_cloud_firestore_test.dart
https://github.com/atn832/fake_cloud_firestore/issues/221
Let me know if one of those tests aren't required. I was curious if it would maintain the sub collections, that's why I wrote one for that case.
> Delete reflects on docsData

- lib/src/mock_document_reference.dart
- lib/src/mock_field_value_platform.dart
- lib/src/mock_query.dart
- lib/src/util.dart
- test/mock_query_test.dart
Fix:
`FieldPath.documentID` should be matched against `DocumentReference`.
> where with FieldPath.documentID and DocumentReference

- lib/src/mock_query.dart
- test/mock_query_test.dart
Increased limit on `whereIn` and `arrayContainsAny` queries per updated Firestore docs: 
https://firebase.google.com/docs/firestore/query-data/queries#limitations_2
> fix: increased limit `whereIn` and `arrayContainsAny` disjunctions

- lib/src/fake_cloud_firestore_instance.dart
- lib/src/fake_query_with_parent.dart
- lib/src/query_snapshot_stream_manager.dart
- test/fake_cloud_firestore_test.dart
Changes:
- Added `clearPersistence()` implementation to clear fake cloud firestore
> Implement `clearPersistence` to wipe fake database

- lib/src/fake_cloud_firestore_instance.dart
- lib/src/fake_converted_query.dart
- lib/src/mock_collection_reference.dart
- lib/src/mock_document_reference.dart
- lib/src/mock_query.dart
- lib/src/mock_query_snapshot.dart
- lib/src/query_snapshot_stream_manager.dart
- test/mock_query_test.dart
Fix for #224 . 
Also fixed proper snapshot query emitting when document modified/removed preserving old and new indexes.
> Fix `docChanges` removed, modified and added with proper index values

- .github/workflows/dart-format.yaml
I had not realized that the google/dart Docker account had been discontinued: https://hub.docker.com/r/google/dart/tags. It was shipping with Dart 2.15.1 and couldn't parse our newer Dart 3.0.0 code.
https://github.com/atn832/fake_cloud_firestore/actions/runs/7519020088/job/20467064770
> DART_VERSION=2.15.1
The new account is https://hub.docker.com/_/dart.
> fix dart-format workflow: upgrade dart image

- lib/src/mock_document_snapshot.dart
- test/mock_query_test.dart
Fixes null check operation on null value when queried with composite keys on null data document.
Fix for: #297
> fix: composite key query on null document

- lib/src/mock_document_reference.dart
- lib/src/mock_document_snapshot.dart
- test/fake_cloud_firestore_test.dart
> fix: set({}) followed by get() returns {}

- lib/src/fake_query_with_parent.dart
- lib/src/mock_document_reference.dart
- pubspec.yaml
Add the missing `source` argument added in Firebase 4.17.0
Fixes #305
> Add source argument to support cloud_firestore 4.17.0

- analysis_options.yaml
- example/analysis_options.yaml
- lib/src/query_snapshot_stream_manager.dart
- test/query_snapshot_stream_manager_test.dart
Snapshot listeners built with a converter will not hear updates made from a reference without a converter
Fixes #294 
Re added the previous code we had before #284 when the query type doesn't match, I couldn't think of a better solution but I'm open to ideas.
> fix: compatibility for listeners with different converters

- lib/src/query_snapshot_stream_manager.dart
- test/mock_query_test.dart
Changes:
- Fixed the wrong docs change state (missing change info) on the snapshots when docs are saved in parallel
> fix: multiple docs change for parallel saved doc snapshots

- lib/src/mock_document_snapshot.dart
- lib/src/mock_query_document_snapshot.dart
- lib/src/query_snapshot_stream_manager.dart
- test/mock_query_test.dart
#312 supported the case when two documents are added in parallel and we want to fire an event that includes both additions. This PR supports any parallel modification, such as when two documents are removed or modified in parallel.
> support firing multiple removals when done in parallel

- CHANGELOG.md
- pubspec.yaml
Hey! Thanks for this useful plugin!
I took the chance to bump rxdart to ^0.28.0 as many new libraries target this specific version.
Fixes #315
> Bumped rxdart version to ^0.28.0

- lib/src/mock_query.dart
- test/mock_query_test.dart
This PR addresses the following:
1. Fixes an issue when ordering by multiple fields with different sort orders
2. Closes #293 with support for Filter.or and Filter.and
> Fix order by multiple field with different orders and added Filter support.

- .github/workflows/dart-format.yaml
- .gitignore
- analysis_options.yaml
- pubspec.yaml
Looks like pedantic was discontinued 4 years ago. https://pub.dev/packages/pedantic
https://www.reddit.com/r/FlutterDev/comments/oc3hs8/pedantic_and_effective_dart_are_deprecated/#:~:text=Pedantic%20and%20Effective%20Dart%20are,relative%20package/reorder%20packages%20lints.
https://pub.dev/packages/flutter_lints
> fix dart format workflow: migrate from pedantic to flutter_lints
